---

stages:
  - build
  - test_seeds
  - test_solutions
  - report

default:
  before_script:
    - ./scripts/build.sh --copy-files
    - git apply patches/jq_no_cmdline.patch

include:
  - scripts/CI/base.yml
  - scripts/CI/test_solutions_gcc.yml
  - scripts/CI/test_solutions_afl-clang-fast.yml
  - scripts/CI/test_solutions_afl-clang-fast-64.yml
  - scripts/CI/honggfuzz.yml
  - scripts/CI/test_solutions_honggfuzz.yml
  - scripts/CI/angora.yml
  - scripts/CI/lava-m.yml

build:afl-gcc:
  extends: .build
  variables:
    PREFIX: "lava-afl-gcc"
  script:
    - ./scripts/build.sh --cc afl-gcc
  artifacts:
    expire_in: 6 mos

build:afl-clang-fast:
  extends: .build
  artifacts:
    expire_in: 6 mos
  only:
    - tags

build:afl-clang-fast-dev:
  extends: .build
  image:
    name: registry.gitlab.com/rode0day/fuzzer-testing/i386/aflpp_runner:16.04
  artifacts:
    expire_in: 6 mos
  only:
    - dev

build:gcc-64:
  extends: .build
  variables:
    PREFIX: "lava-gcc"
  image:
    name: registry.gitlab.com/rode0day/fuzzer-testing/afl_runner:16.04
  script:
    - ./scripts/build.sh --cc gcc -X

build:afl-clang-fast-64:
  extends: .build
  image:
    name: registry.gitlab.com/rode0day/fuzzer-testing/afl_runner:16.04
  script:
    - ./scripts/build.sh -X

test_seeds:afl-gcc:
  extends: .test_seeds
  variables:
    PREFIX: "lava-afl-gcc"
  dependencies:
    - build:afl-gcc

test_seeds:afl-clang-fast:
  extends: .test_seeds
  dependencies:
    - build:afl-clang-fast
    - build:afl-clang-fast-dev

test_seeds:gcc-64:
  extends: .test_seeds
  variables:
    PREFIX: "lava-gcc"
  dependencies:
    - build:gcc-64

test_seeds:afl-clang-fast-64:
  extends: .test_seeds
  dependencies:
    - build:afl-clang-fast-64

pages:
  stage: report
  before_script:
    - echo "ignoring default before_script"
  script:
    - ./scripts/generate_report.sh
  artifacts:
    paths:
      - public
  only:
    - tags
