---

stages:
    - build
    - test_seeds
    - test_solutions

build:all:
  stage: build
  image: 
    name: registry.gitlab.com/rode0day/fuzzer-testing/i386/aflpp_runner:16.04
    entrypoint: [""]
  script:
    - ( cd 10 && ./fix_tcpdump_for_i386.sh )
    - ./scripts/build.sh
    - ./scripts/build.sh --cc afl-gcc
  artifacts:
    paths:
      - ./*/*/lava-afl-gcc
      - ./*/*/lava-afl-cf
    expire_in: 1 week

test_seeds:afl-clang:
  stage: test_seeds
  image: 
    name: registry.gitlab.com/rode0day/fuzzer-testing/i386/aflpp_runner:16.04 
    entrypoint: [""]
  script:
    - ./scripts/build.sh --copy-files
    - ./scripts/test-solution.py -p lava-afl-cf 3/info.yaml
    - ./scripts/test-solution.py -p lava-afl-cf 4/info.yaml
    - ./scripts/test-solution.py -p lava-afl-cf 5/info.yaml
  dependencies:
    - build:all

test_solutions:3:9:afl-gcc:
  stage: test_solutions
  image: 
    name: registry.gitlab.com/rode0day/fuzzer-testing/i386/aflpp_runner:16.04 
    entrypoint: [""]
  script:
    - ./scripts/build.sh --copy-files
    - tar -C 3 -xzf 3/solutions.tgz
    - ./scripts/test-solution.py -p lava-afl-gcc 3/info.yaml
  dependencies:
    - build:all

test_solutions:4:9:afl-gcc:
  stage: test_solutions
  image: 
    name: registry.gitlab.com/rode0day/fuzzer-testing/i386/aflpp_runner:16.04 
    entrypoint: [""]
  script:
    - ./scripts/build.sh --copy-files
    - tar -C 4 -xzf 4/solutions.tgz
    - ./scripts/test-solution.py -p lava-afl-gcc 3/info.yaml
  dependencies:
    - build:all

build:hfuzz:
  stage: build
  image: 
    name: registry.gitlab.com/rode0day/fuzzer-testing/i386/honggfuzz_runner:16.04
    entrypoint: [ "" ]
  script:
    - ( cd 10 && ./fix_tcpdump_for_i386.sh )
    - ./scripts/build.sh
    - make -C 13/fileS4/src/src hfuzz-file
    - cp 13/fileS4/src/src/hfuzz-file 13/fileS4/lava-hf/
  artifacts:
    paths:
      - ./*/*/lava-hf
    expire_in: 1 week

test_seeds:hfuzz:
  stage: test_seeds
  image: 
    name: registry.gitlab.com/rode0day/fuzzer-testing/i386/honggfuzz_runner:16.04 
    entrypoint: [ "" ]
  script:
    - ./scripts/build.sh --copy-files
    - ./scripts/test-solution.py -p lava-hf 3/info.yaml
    - ./scripts/test-solution.py -p lava-hf 4/info.yaml
    - ./scripts/test-solution.py -p lava-hf 5/info.yaml
    - ./scripts/test-solution.py -p lava-hf 6/info.yaml
  dependencies:
    - build:hfuzz


build:angora:
  stage: build
  image: 
    name: registry.gitlab.com/rode0day/fuzzer-testing/angora_runner:16.04 
    entrypoint: [""]
  script:
    - sed -i 's/ 10 / /' scripts/build.sh 
    - ./scripts/build.sh --angora -X
  artifacts:
    paths:
      - ./*/*/lava-ang
    expire_in: 1 week

test_seeds:angora:
  stage: test_seeds
  image: 
    name: registry.gitlab.com/rode0day/fuzzer-testing/angora_runner:16.04 
    entrypoint: [""]
  script:
    - sed -i 's/ 10 / /' scripts/build.sh 
    - ./scripts/build.sh --angora -X --copy-files
    - ./scripts/test-solution.py -p lava-ang 3/info.yaml
    - ./scripts/test-solution.py -p lava-ang 4/info.yaml
    - ./scripts/test-solution.py -p lava-ang 5/info.yaml
    - ./scripts/test-solution.py -p lava-ang 6/info.yaml
    - ./scripts/test-solution.py -p lava-ang 7/info.yaml
    - ./scripts/test-solution.py -p lava-ang 8/info.yaml
    - ./scripts/test-solution.py -p lava-ang 9/info.yaml
  dependencies:
    - build:angora
