---

stages:
  - build
  - test_seeds
  - test_solutions
  - report

before_script:
  - ./scripts/build.sh --copy-files

include:
  - scripts/CI/base.yml
  - scripts/CI/test_solutions_gcc.yml
  - scripts/CI/test_solutions_afl-clang-fast.yml
  - scripts/CI/honggfuzz.yml
  - scripts/CI/test_solutions_honggfuzz.yml
  - scripts/CI/angora.yml

build:afl-gcc:
  extends: .build
  script:
    - ( cd 10 && ./fix_tcpdump_for_i386.sh )
    - ./scripts/build.sh --cc afl-gcc
  artifacts:
    paths:
      - ./*/*/lava-afl-gcc

build:afl-clang-fast:
  extends: .build
  script:
    - ( cd 10 && ./fix_tcpdump_for_i386.sh )
    - ./scripts/build.sh
  artifacts:
    paths:
      - ./*/*/lava-afl-cf

build:afl-gcc-64:
  extends: .build
  image:
    name: registry.gitlab.com/rode0day/fuzzer-testing/afl_runner:16.04
  script:
    - ( cd 10 && ./fix_tcpdump_for_x86_64.sh )
    - ./scripts/build.sh --cc afl-gcc -X
  artifacts:
    paths:
      - ./*/*/lava-afl-gcc
  allow_failure: true

build:afl-clang-fast-64:
  extends: .build
  image:
    name: registry.gitlab.com/rode0day/fuzzer-testing/afl_runner:16.04
  script:
    - ( cd 10 && ./fix_tcpdump_for_x86_64.sh )
    - sed -i 's/ 10 / /' scripts/build.sh
    - ./scripts/build.sh -X
  artifacts:
    paths:
      - ./*/*/lava-afl-cf

test_seeds:1:4:afl:
  extends: .test_seeds
  script:
    - ./scripts/test-solution.py -p lava-afl-gcc 3/info.yaml 4/info.yaml
      5/info.yaml 6/info.yaml 7/info.yaml 8/info.yaml 9/info.yaml
      10/info.yaml 11/info.yaml 12/info.yaml 13/info.yaml
  dependencies:
    - build:afl-gcc

test_seeds:2:4:afl:
  extends: .test_seeds
  stage: test_seeds
  script:
    - ./scripts/test-solution.py -p lava-afl-cf 3/info.yaml 4/info.yaml
      5/info.yaml 6/info.yaml 7/info.yaml 8/info.yaml 9/info.yaml
      10/info.yaml 11/info.yaml 12/info.yaml 13/info.yaml
  dependencies:
    - build:afl-clang-fast

test_seeds:3:4:afl:
  extends: .test_seeds
  script:
    - ./scripts/test-solution.py -p lava-afl-gcc 3/info.yaml 4/info.yaml
      5/info.yaml 6/info.yaml 7/info.yaml 8/info.yaml 9/info.yaml
      10/info.yaml 11/info.yaml 12/info.yaml 13/info.yaml
  dependencies:
    - build:afl-gcc-64

test_seeds:4:4:afl:
  extends: .test_seeds
  script:
    - ./scripts/test-solution.py -p lava-afl-cf 3/info.yaml 4/info.yaml
      5/info.yaml 6/info.yaml 7/info.yaml 8/info.yaml 9/info.yaml
      10/info.yaml 11/info.yaml 12/info.yaml 13/info.yaml
  dependencies:
    - build:afl-clang-fast-64

pages:
  stage: report
  before_script:
    - echo "ignoring default before_script"
  script:
    - ./scripts/generate_report.sh
  artifacts:
    paths:
      - public
  only:
    - master
