
.build:
  stage: build
  image: 
    name: registry.gitlab.com/rode0day/fuzzer-testing/i386/afl_runner:16.04
    entrypoint: [""]
  artifacts:
    expire_in: 1 week

.test_seeds:
  stage: test_seeds
  image: 
    name: registry.gitlab.com/rode0day/fuzzer-testing/afl_runner:16.04 
    entrypoint: [""]

.test_solutions:
  stage: test_solutions
  image: 
    name: registry.gitlab.com/rode0day/fuzzer-testing/afl_runner:16.04
    entrypoint: [""]
  script:
    - echo $COMP_ID $PREFIX
    - tar -C $COMP_ID -xzf ${COMP_ID}/solutions.tgz
    - ./scripts/test-solution.py -p $PREFIX ${COMP_ID}/info.yaml
  artifacts:
    paths:
      - results*.html 
    expire_in: 1 week
  only:
    - master
